// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry              = require("bs-platform/lib/js/curry.js");
var Respect            = require("../src/Respect.js");
var Caml_oo_curry      = require("bs-platform/lib/js/caml_oo_curry.js");
var Respect_matchersV2 = require("../src/Respect_matchersV2.js");

function shouldMatch(fn, don) {
  return Curry._1(fn, (function (err, _) {
                if (err) {
                  return Curry._2(don, /* Some */[err[0]], /* () */0);
                } else {
                  return Curry._2(don, /* None */0, /* () */0);
                }
              }));
}

function shouldNotMatch(fn, don) {
  return Curry._1(fn, (function (err, _) {
                if (err) {
                  return Curry._2(don, /* None */0, /* () */0);
                } else {
                  return Curry._2(don, /* Some */["Expected match error, but none was received"], /* () */0);
                }
              }));
}

Curry._1(Respect.Dsl[/* Async */12][/* register */3], Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "MatchersV2", /* :: */[
          Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "equal", /* :: */[
                Curry._2(Respect.Dsl[/* Async */12][/* it */1], "matches when args are equal", (function () {
                        var tmp = Respect_matchersV2.expect(5);
                        var partial_arg = Caml_oo_curry.js2(5793412, 1, tmp, Respect_matchersV2.equal(5));
                        return (function (param) {
                            return shouldMatch(partial_arg, param);
                          });
                      })),
                /* :: */[
                  Curry._2(Respect.Dsl[/* Async */12][/* it */1], "fails when args are not equal", (function () {
                          var tmp = Respect_matchersV2.expect(5);
                          var partial_arg = Caml_oo_curry.js2(5793412, 2, tmp, Respect_matchersV2.equal(6));
                          return (function (param) {
                              return shouldNotMatch(partial_arg, param);
                            });
                        })),
                  /* [] */0
                ]
              ]),
          /* [] */0
        ]));

exports.shouldMatch    = shouldMatch;
exports.shouldNotMatch = shouldNotMatch;
/*  Not a pure module */
