// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Async                           = require("re-sync/lib/js/src/Async.js");
var Curry                           = require("bs-platform/lib/js/curry.js");
var Pervasives                      = require("bs-platform/lib/js/pervasives.js");
var Caml_exceptions                 = require("bs-platform/lib/js/caml_exceptions.js");
var Respect$Stroimanrespect         = require("../src/Respect.js");
var Respect_ctx$Stroimanrespect     = require("../src/Respect_ctx.js");
var Respect_dsl$Stroimanrespect     = require("../src/Respect_dsl.js");
var TestHelpers$Stroimanrespect     = require("./TestHelpers.js");
var Respect_matcher$Stroimanrespect = require("../src/Respect_matcher.js");

var MockFailure = Caml_exceptions.create("RunnerSpecs-Stroimanrespect.MockFailure");

var run = Respect$Stroimanrespect.Runner[/* run */3];

function runAndReturn(res, examples) {
  var partial_arg = run(examples);
  return (function (param) {
      return Async.map((function () {
                    return res[0];
                  }), partial_arg, param);
    });
}

function beSuccess(actual) {
  var match = Curry._1(Respect$Stroimanrespect.Runner[/* RunResult */1][/* getResult */6], actual);
  if (match !== 1) {
    return (function (param) {
        return Respect_matcher$Stroimanrespect.matchFailure(actual, actual, param);
      });
  } else {
    return (function (param) {
        return Respect_matcher$Stroimanrespect.matchSuccess(actual, param);
      });
  }
}

function beFailure(actual) {
  var match = Curry._1(Respect$Stroimanrespect.Runner[/* RunResult */1][/* getResult */6], actual);
  if (match >= 2) {
    return (function (param) {
        return Respect_matcher$Stroimanrespect.matchSuccess(actual, param);
      });
  } else {
    return (function (param) {
        return Respect_matcher$Stroimanrespect.matchFailure(actual, actual, param);
      });
  }
}

function bePending(actual) {
  var match = Curry._1(Respect$Stroimanrespect.Runner[/* RunResult */1][/* getResult */6], actual);
  if (match !== 0) {
    return (function (param) {
        return Respect_matcher$Stroimanrespect.matchFailure(actual, actual, param);
      });
  } else {
    return (function (param) {
        return Respect_matcher$Stroimanrespect.matchSuccess(actual, param);
      });
  }
}

Respect_dsl$Stroimanrespect.Async[/* register */3](Respect_dsl$Stroimanrespect.Async[/* describe */2]("Runner", /* :: */[
          Respect_dsl$Stroimanrespect.Async[/* describe */2]("Group has 3 passing, two pending, and one failing test", /* :: */[
                Respect_dsl$Stroimanrespect.Async[/* beforeEach */4]((function (ctx, don) {
                        var arg = /* Some */[(function (param, param$1) {
                              return TestHelpers$Stroimanrespect.failingExample(/* None */0, /* () */0, param, param$1);
                            })];
                        var arg$1 = /* Some */[(function (param, param$1) {
                              return TestHelpers$Stroimanrespect.pendingExample(/* None */0, /* () */0, param, param$1);
                            })];
                        var arg$2 = /* Some */[(function (param, param$1) {
                              return TestHelpers$Stroimanrespect.pendingExample(/* None */0, /* () */0, param, param$1);
                            })];
                        var arg$3 = /* Some */[(function (param, param$1) {
                              return TestHelpers$Stroimanrespect.passingExample(/* None */0, /* () */0, param, param$1);
                            })];
                        var arg$4 = /* Some */[(function (param, param$1) {
                              return TestHelpers$Stroimanrespect.passingExample(/* None */0, /* () */0, param, param$1);
                            })];
                        var arg$5 = /* Some */[(function (param, param$1) {
                              return TestHelpers$Stroimanrespect.passingExample(/* None */0, /* () */0, param, param$1);
                            })];
                        var ex = (function (eta) {
                              return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg, eta);
                            })((function (eta) {
                                  return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$1, eta);
                                })((function (eta) {
                                      return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$2, eta);
                                    })((function (eta) {
                                          return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$3, eta);
                                        })((function (eta) {
                                              return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$4, eta);
                                            })((function (eta) {
                                                  return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$5, eta);
                                                })(TestHelpers$Stroimanrespect.anExampleGroup))))));
                        return Async.run(/* None */0, (function (x) {
                                      Respect_ctx$Stroimanrespect.add("result", x, ctx);
                                      return Curry._2(don, /* None */0, /* () */0);
                                    }), run(ex));
                      })),
                /* :: */[
                  Respect_dsl$Stroimanrespect.Async[/* it */1]("reports 3 passed", (function (ctx) {
                          var partial_arg = Curry._1(Respect$Stroimanrespect.Runner[/* RunResult */1][/* getNoOfPassedTests */3], Respect_ctx$Stroimanrespect.get("result", ctx));
                          return (function (param) {
                              return Respect_matcher$Stroimanrespect.shoulda((function (param) {
                                            return Respect_matcher$Stroimanrespect.equal(3, param);
                                          }), partial_arg, param);
                            });
                        })),
                  /* :: */[
                    Respect_dsl$Stroimanrespect.Async[/* it */1]("Is success when all tests succeed", (function () {
                            var arg = /* Some */[(function (param, param$1) {
                                  return TestHelpers$Stroimanrespect.passingExample(/* None */0, /* () */0, param, param$1);
                                })];
                            var arg$1 = /* Some */[(function (param, param$1) {
                                  return TestHelpers$Stroimanrespect.passingExample(/* None */0, /* () */0, param, param$1);
                                })];
                            var ex = (function (eta) {
                                  return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg, eta);
                                })((function (eta) {
                                      return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$1, eta);
                                    })(TestHelpers$Stroimanrespect.anExampleGroup));
                            var partial_arg = run(ex);
                            var partial_arg$1 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                            var partial_arg$2 = function (param, param$1) {
                              return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$1, beSuccess, param, param$1);
                            };
                            return (function (param) {
                                return Respect_matcher$Stroimanrespect.shoulda(partial_arg$2, partial_arg, param);
                              });
                          })),
                    /* :: */[
                      Respect_dsl$Stroimanrespect.Async[/* it */1]("Is pending when one test is pending", (function () {
                              var arg = /* Some */[(function (param, param$1) {
                                    return TestHelpers$Stroimanrespect.pendingExample(/* None */0, /* () */0, param, param$1);
                                  })];
                              var arg$1 = /* Some */[(function (param, param$1) {
                                    return TestHelpers$Stroimanrespect.passingExample(/* None */0, /* () */0, param, param$1);
                                  })];
                              var ex = (function (eta) {
                                    return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg, eta);
                                  })((function (eta) {
                                        return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$1, eta);
                                      })(TestHelpers$Stroimanrespect.anExampleGroup));
                              var partial_arg = run(ex);
                              var partial_arg$1 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                              var partial_arg$2 = function (param, param$1) {
                                return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$1, bePending, param, param$1);
                              };
                              return (function (param) {
                                  return Respect_matcher$Stroimanrespect.shoulda(partial_arg$2, partial_arg, param);
                                });
                            })),
                      /* :: */[
                        Respect_dsl$Stroimanrespect.Async[/* it */1]("Is a failure when one test is pending", (function () {
                                var arg = /* Some */[(function (param, param$1) {
                                      return TestHelpers$Stroimanrespect.failingExample(/* None */0, /* () */0, param, param$1);
                                    })];
                                var arg$1 = /* Some */[(function (param, param$1) {
                                      return TestHelpers$Stroimanrespect.pendingExample(/* None */0, /* () */0, param, param$1);
                                    })];
                                var arg$2 = /* Some */[(function (param, param$1) {
                                      return TestHelpers$Stroimanrespect.passingExample(/* None */0, /* () */0, param, param$1);
                                    })];
                                var ex = (function (eta) {
                                      return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg, eta);
                                    })((function (eta) {
                                          return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$1, eta);
                                        })((function (eta) {
                                              return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$2, eta);
                                            })(TestHelpers$Stroimanrespect.anExampleGroup)));
                                var partial_arg = run(ex);
                                var partial_arg$1 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                                var partial_arg$2 = function (param, param$1) {
                                  return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$1, beFailure, param, param$1);
                                };
                                return (function (param) {
                                    return Respect_matcher$Stroimanrespect.shoulda(partial_arg$2, partial_arg, param);
                                  });
                              })),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]),
          /* :: */[
            Respect_dsl$Stroimanrespect.Async[/* describe */2]("Group has a setup", /* :: */[
                  Respect_dsl$Stroimanrespect.Async[/* it */1]("Doesn't execute example code when setup code fails", (function () {
                          var lines = [/* [] */0];
                          var append = function (line) {
                            lines[0] = Pervasives.$at(lines[0], /* :: */[
                                  line,
                                  /* [] */0
                                ]);
                            return /* () */0;
                          };
                          var eta = TestHelpers$Stroimanrespect.withSetup((function (_, cb) {
                                    append("setup");
                                    return Curry._1(cb, /* TestFailed */2);
                                  }))(TestHelpers$Stroimanrespect.anExampleGroup);
                          var arg = /* Some */[(function (_, cb) {
                                append("test");
                                return Curry._1(cb, /* TestSucceeded */1);
                              })];
                          var ex = Curry._1((function (param, param$1) {
                                    return (function (param$2) {
                                        return TestHelpers$Stroimanrespect.withExample(param, param$1, arg, param$2);
                                      });
                                  })(/* None */0, /* None */0), eta);
                          var partial_arg = runAndReturn(lines, ex);
                          var partial_arg$1 = /* :: */[
                            "setup",
                            /* [] */0
                          ];
                          var partial_arg$2 = function (param) {
                            return Respect_matcher$Stroimanrespect.equal(partial_arg$1, param);
                          };
                          var partial_arg$3 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                          var partial_arg$4 = function (param, param$1) {
                            return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$3, partial_arg$2, param, param$1);
                          };
                          return (function (param) {
                              return Respect_matcher$Stroimanrespect.shoulda(partial_arg$4, partial_arg, param);
                            });
                        })),
                  /* :: */[
                    Respect_dsl$Stroimanrespect.Async[/* it */1]("Executes multiple setups before the example", (function () {
                            var lines = [/* [] */0];
                            var append = function (line, _) {
                              lines[0] = Pervasives.$at(lines[0], /* :: */[
                                    line,
                                    /* [] */0
                                  ]);
                              return /* () */0;
                            };
                            var partial_arg = /* Some */[(function (param) {
                                  return append("test", param);
                                })];
                            var arg = /* Some */[(function (param, param$1) {
                                  return TestHelpers$Stroimanrespect.passingExample(partial_arg, /* () */0, param, param$1);
                                })];
                            var partial_arg$1 = /* Some */[(function (param) {
                                  return append("setup 2", param);
                                })];
                            var partial_arg$2 = /* Some */[(function (param) {
                                  return append("setup 1", param);
                                })];
                            var ex = (function (eta) {
                                  return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg, eta);
                                })(TestHelpers$Stroimanrespect.withSetup((function (param, param$1) {
                                          return TestHelpers$Stroimanrespect.passingSetup(partial_arg$1, /* () */0, param, param$1);
                                        }))(TestHelpers$Stroimanrespect.withSetup((function (param, param$1) {
                                              return TestHelpers$Stroimanrespect.passingSetup(partial_arg$2, /* () */0, param, param$1);
                                            }))(TestHelpers$Stroimanrespect.anExampleGroup)));
                            var partial_arg$3 = runAndReturn(lines, ex);
                            var partial_arg$4 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                            var partial_arg$5 = function (param, param$1) {
                              return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$4, (function (param) {
                                            return Respect_matcher$Stroimanrespect.equal(/* :: */[
                                                        "setup 1",
                                                        /* :: */[
                                                          "setup 2",
                                                          /* :: */[
                                                            "test",
                                                            /* [] */0
                                                          ]
                                                        ]
                                                      ], param);
                                          }), param, param$1);
                            };
                            return (function (param) {
                                return Respect_matcher$Stroimanrespect.shoulda(partial_arg$5, partial_arg$3, param);
                              });
                          })),
                    /* :: */[
                      Respect_dsl$Stroimanrespect.Async[/* it */1]("Executes the setup code before the example", (function () {
                              var lines = [/* [] */0];
                              var append = function (line, _) {
                                lines[0] = Pervasives.$at(lines[0], /* :: */[
                                      line,
                                      /* [] */0
                                    ]);
                                return /* () */0;
                              };
                              var partial_arg = /* Some */[(function (param) {
                                    return append("test", param);
                                  })];
                              var arg = /* Some */[(function (param, param$1) {
                                    return TestHelpers$Stroimanrespect.passingExample(partial_arg, /* () */0, param, param$1);
                                  })];
                              var partial_arg$1 = /* Some */[(function (param) {
                                    return append("setup", param);
                                  })];
                              var ex = (function (eta) {
                                    return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg, eta);
                                  })(TestHelpers$Stroimanrespect.withSetup((function (param, param$1) {
                                            return TestHelpers$Stroimanrespect.passingSetup(partial_arg$1, /* () */0, param, param$1);
                                          }))(TestHelpers$Stroimanrespect.anExampleGroup));
                              var partial_arg$2 = runAndReturn(lines, ex);
                              var partial_arg$3 = /* :: */[
                                "setup",
                                /* :: */[
                                  "test",
                                  /* [] */0
                                ]
                              ];
                              var partial_arg$4 = function (param) {
                                return Respect_matcher$Stroimanrespect.equal(partial_arg$3, param);
                              };
                              var partial_arg$5 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                              var partial_arg$6 = function (param, param$1) {
                                return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$5, partial_arg$4, param, param$1);
                              };
                              return (function (param) {
                                  return Respect_matcher$Stroimanrespect.shoulda(partial_arg$6, partial_arg$2, param);
                                });
                            })),
                      /* :: */[
                        Respect_dsl$Stroimanrespect.Async[/* describe */2]("Group has two examples", /* :: */[
                              Respect_dsl$Stroimanrespect.Async[/* it */1]("Runs the setup before each example", (function () {
                                      var lines = [/* [] */0];
                                      var append = function (line, _) {
                                        lines[0] = Pervasives.$at(lines[0], /* :: */[
                                              line,
                                              /* [] */0
                                            ]);
                                        return /* () */0;
                                      };
                                      var partial_arg = /* Some */[(function (param) {
                                            return append("test 2", param);
                                          })];
                                      var arg = /* Some */[(function (param, param$1) {
                                            return TestHelpers$Stroimanrespect.passingExample(partial_arg, /* () */0, param, param$1);
                                          })];
                                      var partial_arg$1 = /* Some */[(function (param) {
                                            return append("test 1", param);
                                          })];
                                      var arg$1 = /* Some */[(function (param, param$1) {
                                            return TestHelpers$Stroimanrespect.passingExample(partial_arg$1, /* () */0, param, param$1);
                                          })];
                                      var partial_arg$2 = /* Some */[(function (param) {
                                            return append("setup", param);
                                          })];
                                      var ex = (function (eta) {
                                            return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg, eta);
                                          })((function (eta) {
                                                return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$1, eta);
                                              })(TestHelpers$Stroimanrespect.withSetup((function (param, param$1) {
                                                        return TestHelpers$Stroimanrespect.passingSetup(partial_arg$2, /* () */0, param, param$1);
                                                      }))(TestHelpers$Stroimanrespect.anExampleGroup)));
                                      var partial_arg$3 = runAndReturn(lines, ex);
                                      var partial_arg$4 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                                      var partial_arg$5 = function (param, param$1) {
                                        return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$4, (function (param) {
                                                      return Respect_matcher$Stroimanrespect.equal(/* :: */[
                                                                  "setup",
                                                                  /* :: */[
                                                                    "test 1",
                                                                    /* :: */[
                                                                      "setup",
                                                                      /* :: */[
                                                                        "test 2",
                                                                        /* [] */0
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ], param);
                                                    }), param, param$1);
                                      };
                                      return (function (param) {
                                          return Respect_matcher$Stroimanrespect.shoulda(partial_arg$5, partial_arg$3, param);
                                        });
                                    })),
                              /* [] */0
                            ]),
                        /* :: */[
                          Respect_dsl$Stroimanrespect.Async[/* describe */2]("Nested groups", /* :: */[
                                Respect_dsl$Stroimanrespect.Async[/* it */1]("Runs the setups from outermost to innermost group", (function () {
                                        var lines = [/* [] */0];
                                        var append = function (line, _) {
                                          lines[0] = Pervasives.$at(lines[0], /* :: */[
                                                line,
                                                /* [] */0
                                              ]);
                                          return /* () */0;
                                        };
                                        var partial_arg = /* Some */[(function (param) {
                                              return append("inner test", param);
                                            })];
                                        var arg = /* Some */[(function (param, param$1) {
                                              return TestHelpers$Stroimanrespect.passingExample(partial_arg, /* () */0, param, param$1);
                                            })];
                                        var partial_arg$1 = /* Some */[(function (param) {
                                              return append("inner setup", param);
                                            })];
                                        var innerGroup = (function (eta) {
                                              return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg, eta);
                                            })(TestHelpers$Stroimanrespect.withSetup((function (param, param$1) {
                                                      return TestHelpers$Stroimanrespect.passingSetup(partial_arg$1, /* () */0, param, param$1);
                                                    }))(TestHelpers$Stroimanrespect.anExampleGroup));
                                        var partial_arg$2 = /* Some */[(function (param) {
                                              return append("outer test", param);
                                            })];
                                        var arg$1 = /* Some */[(function (param, param$1) {
                                              return TestHelpers$Stroimanrespect.passingExample(partial_arg$2, /* () */0, param, param$1);
                                            })];
                                        var partial_arg$3 = /* Some */[(function (param) {
                                              return append("outer setup", param);
                                            })];
                                        var outerGroup = TestHelpers$Stroimanrespect.withChildGroup(innerGroup, (function (eta) {
                                                  return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg$1, eta);
                                                })(TestHelpers$Stroimanrespect.withSetup((function (param, param$1) {
                                                          return TestHelpers$Stroimanrespect.passingSetup(partial_arg$3, /* () */0, param, param$1);
                                                        }))(TestHelpers$Stroimanrespect.anExampleGroup)));
                                        var partial_arg$4 = runAndReturn(lines, outerGroup);
                                        var partial_arg$5 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                                        var partial_arg$6 = function (param, param$1) {
                                          return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$5, (function (param) {
                                                        return Respect_matcher$Stroimanrespect.equal(/* :: */[
                                                                    "outer setup",
                                                                    /* :: */[
                                                                      "outer test",
                                                                      /* :: */[
                                                                        "outer setup",
                                                                        /* :: */[
                                                                          "inner setup",
                                                                          /* :: */[
                                                                            "inner test",
                                                                            /* [] */0
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ], param);
                                                      }), param, param$1);
                                        };
                                        return (function (param) {
                                            return Respect_matcher$Stroimanrespect.shoulda(partial_arg$6, partial_arg$4, param);
                                          });
                                      })),
                                /* [] */0
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]),
            /* :: */[
              Respect_dsl$Stroimanrespect.Async[/* describe */2]("ExampleGroup has metadata", /* :: */[
                    Respect_dsl$Stroimanrespect.Async[/* it */1]("Initializes the metadata on the test context", (function () {
                            var data = [""];
                            var partial_arg = /* Some */[(function (ctx) {
                                  data[0] = Respect_ctx$Stroimanrespect.get("data", ctx);
                                  return /* () */0;
                                })];
                            var arg = /* Some */[(function (param, param$1) {
                                  return TestHelpers$Stroimanrespect.passingExample(partial_arg, /* () */0, param, param$1);
                                })];
                            var grp = (function (eta) {
                                  return TestHelpers$Stroimanrespect.withExample(/* None */0, /* None */0, arg, eta);
                                })(TestHelpers$Stroimanrespect.withMetadata(/* tuple */[
                                      "data",
                                      "value"
                                    ], TestHelpers$Stroimanrespect.anExampleGroup));
                            var partial_arg$1 = runAndReturn(data, grp);
                            var partial_arg$2 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                            var partial_arg$3 = function (param, param$1) {
                              return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$2, (function (param) {
                                            return Respect_matcher$Stroimanrespect.equal("value", param);
                                          }), param, param$1);
                            };
                            return (function (param) {
                                return Respect_matcher$Stroimanrespect.shoulda(partial_arg$3, partial_arg$1, param);
                              });
                          })),
                    /* [] */0
                  ]),
              /* :: */[
                Respect_dsl$Stroimanrespect.Async[/* describe */2]("Parent group has metadata", /* :: */[
                      Respect_dsl$Stroimanrespect.Async[/* it */1]("uses the metadata closest to the example", (function () {
                              var lines = [/* [] */0];
                              var append = function (line) {
                                lines[0] = Pervasives.$at(lines[0], /* :: */[
                                      line,
                                      /* [] */0
                                    ]);
                                return /* () */0;
                              };
                              var partial_arg = /* Some */[(function (ctx) {
                                    append(Respect_ctx$Stroimanrespect.get("data1", ctx));
                                    append(Respect_ctx$Stroimanrespect.get("data2", ctx));
                                    return append(Respect_ctx$Stroimanrespect.get("data3", ctx));
                                  })];
                              var arg = /* Some */[(function (param, param$1) {
                                    return TestHelpers$Stroimanrespect.passingExample(partial_arg, /* () */0, param, param$1);
                                  })];
                              var arg$1 = function (param) {
                                return Curry._3(TestHelpers$Stroimanrespect.withExample, /* Some */[/* tuple */[
                                              "data3",
                                              "test"
                                            ]], param, arg);
                              };
                              var innerGroup = (function (eta) {
                                    return Curry._1(arg$1(/* None */0), eta);
                                  })(TestHelpers$Stroimanrespect.withMetadata(/* tuple */[
                                        "data3",
                                        "inner"
                                      ], TestHelpers$Stroimanrespect.withMetadata(/* tuple */[
                                            "data2",
                                            "inner"
                                          ], TestHelpers$Stroimanrespect.anExampleGroup)));
                              var outerGroup = TestHelpers$Stroimanrespect.withChildGroup(innerGroup, TestHelpers$Stroimanrespect.withMetadata(/* tuple */[
                                        "data3",
                                        "outer"
                                      ], TestHelpers$Stroimanrespect.withMetadata(/* tuple */[
                                            "data2",
                                            "outer"
                                          ], TestHelpers$Stroimanrespect.withMetadata(/* tuple */[
                                                "data1",
                                                "outer"
                                              ], TestHelpers$Stroimanrespect.anExampleGroup))));
                              var partial_arg$1 = runAndReturn(lines, outerGroup);
                              var partial_arg$2 = /* :: */[
                                "outer",
                                /* :: */[
                                  "inner",
                                  /* :: */[
                                    "test",
                                    /* [] */0
                                  ]
                                ]
                              ];
                              var partial_arg$3 = function (param) {
                                return Respect_matcher$Stroimanrespect.equal(partial_arg$2, param);
                              };
                              var partial_arg$4 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                              var partial_arg$5 = function (param, param$1) {
                                return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$4, partial_arg$3, param, param$1);
                              };
                              return (function (param) {
                                  return Respect_matcher$Stroimanrespect.shoulda(partial_arg$5, partial_arg$1, param);
                                });
                            })),
                      /* [] */0
                    ]),
                /* :: */[
                  Respect_dsl$Stroimanrespect.Async[/* describe */2]("example throws an exception", /* :: */[
                        Respect_dsl$Stroimanrespect.Async[/* it */1]("returns an error message", (function () {
                                var ex = TestHelpers$Stroimanrespect.withExampleCode((function () {
                                          throw [
                                                MockFailure,
                                                ""
                                              ];
                                        }))(TestHelpers$Stroimanrespect.anExampleGroup);
                                var partial_arg = run(ex);
                                var partial_arg$1 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                                var partial_arg$2 = function (param, param$1) {
                                  return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$1, beFailure, param, param$1);
                                };
                                return (function (param) {
                                    return Respect_matcher$Stroimanrespect.shoulda(partial_arg$2, partial_arg, param);
                                  });
                              })),
                        /* [] */0
                      ]),
                  /* :: */[
                    Respect_dsl$Stroimanrespect.Async[/* it */1]("executes the example code", (function () {
                            var lines = [/* [] */0];
                            var ex = TestHelpers$Stroimanrespect.withExampleCode((function () {
                                      var line = "x";
                                      lines[0] = /* :: */[
                                        line,
                                        lines[0]
                                      ];
                                      return /* () */0;
                                    }))(TestHelpers$Stroimanrespect.anExampleGroup);
                            var partial_arg = runAndReturn(lines, ex);
                            var partial_arg$1 = /* :: */[
                              "x",
                              /* [] */0
                            ];
                            var partial_arg$2 = function (param) {
                              return Respect_matcher$Stroimanrespect.equal(partial_arg$1, param);
                            };
                            var partial_arg$3 = TestHelpers$Stroimanrespect.AsyncMatchers[/* asyncResolve */0];
                            var partial_arg$4 = function (param, param$1) {
                              return Respect_matcher$Stroimanrespect.$great$eq$great(partial_arg$3, partial_arg$2, param, param$1);
                            };
                            return (function (param) {
                                return Respect_matcher$Stroimanrespect.shoulda(partial_arg$4, partial_arg, param);
                              });
                          })),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]));

var As = 0;

var Ctx = 0;

exports.As           = As;
exports.Ctx          = Ctx;
exports.MockFailure  = MockFailure;
exports.run          = run;
exports.runAndReturn = runAndReturn;
exports.beSuccess    = beSuccess;
exports.beFailure    = beFailure;
exports.bePending    = bePending;
/*  Not a pure module */
