// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block                           = require("bs-platform/lib/js/block.js");
var Caml_oo_curry                   = require("bs-platform/lib/js/caml_oo_curry.js");
var Respect_ctx$Stroimanrespect     = require("../src/Respect_ctx.js");
var Respect_dsl$Stroimanrespect     = require("../src/Respect_dsl.js");
var Respect_matcher$Stroimanrespect = require("../src/Respect_matcher.js");

function beFailure(result) {
  if (result >= 2) {
    return /* MatchSuccess */Block.__(0, [/* () */0]);
  } else {
    return /* MatchFailure */Block.__(1, [
              /* () */0,
              /* () */0
            ]);
  }
}

function create() {
  return Respect_ctx$Stroimanrespect.create(Respect_ctx$Stroimanrespect.ContextMap[/* empty */0]);
}

Respect_dsl$Stroimanrespect.Async[/* register */3](Respect_dsl$Stroimanrespect.Async[/* describe */2]("TestContext", /* :: */[
          Respect_dsl$Stroimanrespect.Async[/* describe */2]("done helper for setup", /* :: */[
                Respect_dsl$Stroimanrespect.Async[/* beforeEach */4]((function (ctx) {
                        return Respect_ctx$Stroimanrespect.don(Respect_ctx$Stroimanrespect.add("key", 42, ctx));
                      })),
                /* :: */[
                  Respect_dsl$Stroimanrespect.Async[/* it */1]("Uses value from setup", (function (ctx) {
                          var partial_arg = Respect_ctx$Stroimanrespect.get("key", ctx);
                          return (function (param) {
                              return Respect_matcher$Stroimanrespect.shoulda((function (param) {
                                            return Respect_matcher$Stroimanrespect.equal(42, param);
                                          }), partial_arg, param);
                            });
                        })),
                  /* [] */0
                ]
              ]),
          /* :: */[
            Respect_dsl$Stroimanrespect.Async[/* describe */2]("Get/set data to context", /* :: */[
                  Respect_dsl$Stroimanrespect.Async[/* it */1]("Data added to context is retrievable", (function () {
                          var ctx = Respect_ctx$Stroimanrespect.create(Respect_ctx$Stroimanrespect.ContextMap[/* empty */0]);
                          var tmp = Caml_oo_curry.js3(4846113, 1, ctx, "key", 42);
                          var partial_arg = Caml_oo_curry.js2(5144726, 2, tmp, "key");
                          return (function (param) {
                              return Respect_matcher$Stroimanrespect.shoulda((function (param) {
                                            return Respect_matcher$Stroimanrespect.equal(42, param);
                                          }), partial_arg, param);
                            });
                        })),
                  /* :: */[
                    Respect_dsl$Stroimanrespect.Async[/* it */1]("Data new values overwrite old values", (function () {
                            var ctx = Respect_ctx$Stroimanrespect.create(Respect_ctx$Stroimanrespect.ContextMap[/* empty */0]);
                            var ctx$1 = Caml_oo_curry.js3(4846113, 3, ctx, "key2", 42);
                            var tmp = Caml_oo_curry.js3(4846113, 4, ctx$1, "key", 43);
                            var partial_arg = Caml_oo_curry.js2(5144726, 5, tmp, "key");
                            return (function (param) {
                                return Respect_matcher$Stroimanrespect.shoulda((function (param) {
                                              return Respect_matcher$Stroimanrespect.equal(43, param);
                                            }), partial_arg, param);
                              });
                          })),
                    /* :: */[
                      Respect_dsl$Stroimanrespect.Async[/* it */1]("Subjec to change!!! Context is mutated", (function () {
                              var ctx = Respect_ctx$Stroimanrespect.create(Respect_ctx$Stroimanrespect.ContextMap[/* empty */0]);
                              var tmp = Caml_oo_curry.js3(4846113, 6, ctx, "key", 42);
                              var partial_arg = Caml_oo_curry.js2(5144726, 7, tmp, "key");
                              return (function (param) {
                                  return Respect_matcher$Stroimanrespect.shoulda((function (param) {
                                                return Respect_matcher$Stroimanrespect.equal(42, param);
                                              }), partial_arg, param);
                                });
                            })),
                      /* :: */[
                        Respect_dsl$Stroimanrespect.Async[/* describe */2]("Subject", /* :: */[
                              Respect_dsl$Stroimanrespect.Async[/* it */1]("is not evaluated until used", (function () {
                                      var ctx = Respect_ctx$Stroimanrespect.create(Respect_ctx$Stroimanrespect.ContextMap[/* empty */0]);
                                      var ctx$1 = Respect_ctx$Stroimanrespect.setSubj((function (ctx) {
                                              return Caml_oo_curry.js2(5144726, 8, ctx, "key") + 1 | 0;
                                            }), ctx);
                                      var ctx$2 = Caml_oo_curry.js3(4846113, 9, ctx$1, "key", 42);
                                      var partial_arg = Respect_ctx$Stroimanrespect.subject(ctx$2);
                                      return (function (param) {
                                          return Respect_matcher$Stroimanrespect.shoulda((function (param) {
                                                        return Respect_matcher$Stroimanrespect.equal(43, param);
                                                      }), partial_arg, param);
                                        });
                                    })),
                              /* [] */0
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]),
            /* :: */[
              Respect_dsl$Stroimanrespect.Async[/* describe */2]("Update data", /* :: */[
                    Respect_dsl$Stroimanrespect.Async[/* it */1]("modifies a key based on a function", (function () {
                            var ctx = Respect_ctx$Stroimanrespect.create(Respect_ctx$Stroimanrespect.ContextMap[/* empty */0]);
                            var partial_arg = Respect_ctx$Stroimanrespect.get("key", Respect_ctx$Stroimanrespect.map("key", (function (x) {
                                        return x + 1 | 0;
                                      }), Respect_ctx$Stroimanrespect.add("key", 42, ctx)));
                            return (function (param) {
                                return Respect_matcher$Stroimanrespect.shoulda((function (param) {
                                              return Respect_matcher$Stroimanrespect.equal(43, param);
                                            }), partial_arg, param);
                              });
                          })),
                    /* [] */0
                  ]),
              /* :: */[
                Respect_dsl$Stroimanrespect.Async[/* describe */2]("Access with piping", /* :: */[
                      Respect_dsl$Stroimanrespect.Async[/* it */1]("Can be piped", (function () {
                              var partial_arg = Respect_ctx$Stroimanrespect.get("key", Respect_ctx$Stroimanrespect.add("key", 43, Respect_ctx$Stroimanrespect.add("key", 42, Respect_ctx$Stroimanrespect.create(Respect_ctx$Stroimanrespect.ContextMap[/* empty */0]))));
                              return (function (param) {
                                  return Respect_matcher$Stroimanrespect.shoulda((function (param) {
                                                return Respect_matcher$Stroimanrespect.equal(43, param);
                                              }), partial_arg, param);
                                });
                            })),
                      /* [] */0
                    ]),
                /* :: */[
                  Respect_dsl$Stroimanrespect.Async[/* describe */2]("tryGet", /* :: */[
                        Respect_dsl$Stroimanrespect.Async[/* it */1]("returns Some when data exists", (function () {
                                var partial_arg = Respect_ctx$Stroimanrespect.tryGet("key", Respect_ctx$Stroimanrespect.add("key", 42, Respect_ctx$Stroimanrespect.create(Respect_ctx$Stroimanrespect.ContextMap[/* empty */0])));
                                var partial_arg$1 = /* Some */[42];
                                var partial_arg$2 = function (param) {
                                  return Respect_matcher$Stroimanrespect.equal(partial_arg$1, param);
                                };
                                return (function (param) {
                                    return Respect_matcher$Stroimanrespect.shoulda(partial_arg$2, partial_arg, param);
                                  });
                              })),
                        /* :: */[
                          Respect_dsl$Stroimanrespect.Async[/* it */1]("returns None when data doesn't exist", (function () {
                                  var partial_arg = Respect_ctx$Stroimanrespect.tryGet("key", Respect_ctx$Stroimanrespect.create(Respect_ctx$Stroimanrespect.ContextMap[/* empty */0]));
                                  return (function (param) {
                                      return Respect_matcher$Stroimanrespect.shoulda((function (param) {
                                                    return Respect_matcher$Stroimanrespect.equal(/* None */0, param);
                                                  }), partial_arg, param);
                                    });
                                })),
                          /* [] */0
                        ]
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]));

exports.beFailure = beFailure;
exports.create    = create;
/*  Not a pure module */
