// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry           = require("bs-platform/lib/js/curry.js");
var Js_exn          = require("bs-platform/lib/js/js_exn.js");
var Js_option       = require("bs-platform/lib/js/js_option.js");
var Caml_int32      = require("bs-platform/lib/js/caml_int32.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

function $$return(x, param) {
  return Curry._1(param[0], x);
}

function toMilliseconds(param) {
  if (param.tag) {
    return Caml_int32.imul(param[0], 1000);
  } else {
    return param[0];
  }
}

var JsError = Caml_exceptions.create("Respect_async.JsError");

var Timeout = Caml_exceptions.create("Respect_async.Timeout");

function bind(f, x, param) {
  var errorCB = param[1];
  var successCb = param[0];
  return Curry._1(x, /* tuple */[
              (function (a) {
                  try {
                    return Curry._2(f, a, /* tuple */[
                                successCb,
                                errorCB
                              ]);
                  }
                  catch (raw_x){
                    return Curry._1(errorCB, Js_exn.internalToOCamlException(raw_x));
                  }
                }),
              errorCB
            ]);
}

function map(f, x, param) {
  var errorCb = param[1];
  var successCb = param[0];
  return Curry._1(x, /* tuple */[
              (function (a) {
                  var exit = 0;
                  var x;
                  try {
                    x = Curry._1(f, a);
                    exit = 1;
                  }
                  catch (raw_x){
                    return Curry._1(errorCb, Js_exn.internalToOCamlException(raw_x));
                  }
                  if (exit === 1) {
                    return Curry._1(successCb, x);
                  }
                  
                }),
              errorCb
            ]);
}

function tryCatch(f, x, param) {
  var errorCb = param[1];
  var successCb = param[0];
  return Curry._1(x, /* tuple */[
              successCb,
              (function (x) {
                  var match = Curry._1(f, x);
                  if (match) {
                    return Curry._1(successCb, match[0]);
                  } else {
                    return Curry._1(errorCb, x);
                  }
                })
            ]);
}

function from_js(jsAsync, param) {
  var errorCb = param[1];
  var successCb = param[0];
  return Curry._1(jsAsync, (function (err, s) {
                if (err !== null) {
                  return Curry._1(errorCb, [
                              JsError,
                              err
                            ]);
                } else {
                  return Curry._1(successCb, s);
                }
              }));
}

function timeout(duration, x) {
  var resolved = [/* false */0];
  return (function (param) {
      var errorCb = param[1];
      var successCb = param[0];
      Curry._1(x, /* tuple */[
            (function (x) {
                if (resolved[0]) {
                  return 0;
                } else {
                  resolved[0] = /* true */1;
                  return Curry._1(successCb, x);
                }
              }),
            (function (e) {
                if (resolved[0]) {
                  return 0;
                } else {
                  resolved[0] = /* true */1;
                  return Curry._1(errorCb, e);
                }
              })
          ]);
      setTimeout((function () {
              if (resolved[0]) {
                return 0;
              } else {
                resolved[0] = /* true */1;
                return Curry._1(errorCb, Timeout);
              }
            }), toMilliseconds(duration));
      return /* () */0;
    });
}

function from_callback(fn, param) {
  return Curry._1(fn, param[0]);
}

function run(fe, f, x) {
  return Curry._1(x, /* tuple */[
              f,
              Js_option.getWithDefault((function () {
                      return /* () */0;
                    }), fe)
            ]);
}

exports.$$return       = $$return;
exports.toMilliseconds = toMilliseconds;
exports.JsError        = JsError;
exports.Timeout        = Timeout;
exports.bind           = bind;
exports.map            = map;
exports.tryCatch       = tryCatch;
exports.from_js        = from_js;
exports.timeout        = timeout;
exports.from_callback  = from_callback;
exports.run            = run;
/* No side effect */
