// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry         = require("bs-platform/lib/js/curry.js");
var Respect       = require("./Respect.js");
var Respect_async = require("./Respect_async.js");

function runRoot(callback) {
  return Respect_async.run(/* Some */[(function () {
                  console.log("Test run failed");
                  return Curry._1(callback, 1);
                })], (function (result) {
                if (Respect.TestResult[/* isSuccess */0](result[/* testResult */0])) {
                  console.log("Test run succeeded");
                  return Curry._1(callback, 0);
                } else {
                  console.log("Test run failed");
                  return Curry._1(callback, 1);
                }
              }), Respect.Runner[/* runRoot */4](/* () */0));
}

exports.runRoot = runRoot;
/* Respect Not a pure module */
