// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Async = require("@stroiman/async/lib/js/src/Async.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Respect = require("./Respect.js");

function runRoot(callback) {
  return Async.run(/* Some */[(function () {
                  console.log("Test run failed");
                  return Curry._1(callback, 1);
                })], (function (result) {
                console.log(Curry._1(Respect.Runner[/* RunResult */1][/* getNoOfPassedTests */3], result).toString(), "passed tests,", Curry._1(Respect.Runner[/* RunResult */1][/* getNoOfPendingTests */4], result).toString(), "pending tests, ", Curry._1(Respect.Runner[/* RunResult */1][/* getNoOfFailedTests */5], result).toString(), "failed tests");
                if (Respect.TestResult[/* isSuccess */0](result)) {
                  console.log("Test run succeeded");
                  return Curry._1(callback, 0);
                } else {
                  console.log("Test run failed");
                  return Curry._1(callback, 1);
                }
              }), Respect.Runner[/* runRoot */4](/* () */0));
}

exports.runRoot = runRoot;
/* Async Not a pure module */
