// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry         = require("bs-platform/lib/js/curry.js");
var Respect       = require("./Respect.js");
var Respect_async = require("./Respect_async.js");

function runRoot(callback) {
  return Respect_async.run(/* Some */[(function () {
                  console.log("Test run failed");
                  return Curry._1(callback, 1);
                })], (function (result) {
                console.log(Curry._1(Respect.Runner[/* RunResult */2][/* getNoOfPassedTests */3], result).toString(), "passed tests,", Curry._1(Respect.Runner[/* RunResult */2][/* getNoOfPendingTests */4], result).toString(), "pending tests, ", Curry._1(Respect.Runner[/* RunResult */2][/* getNoOfFailedTests */5], result).toString(), "failed tests");
                if (Respect.TestResult[/* isSuccess */0](result)) {
                  console.log("Test run succeeded");
                  return Curry._1(callback, 0);
                } else {
                  console.log("Test run failed");
                  return Curry._1(callback, 1);
                }
              }), Respect.Runner[/* runRoot */5](/* () */0));
}

exports.runRoot = runRoot;
/* Respect Not a pure module */
