// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry   = require("bs-platform/lib/js/curry.js");
var Respect = require("./Respect.js");

function runRoot(callback) {
  return Respect.Runner[/* runRoot */3]((function (result) {
                if (Respect.TestResult[/* isSuccess */0](result)) {
                  console.log("Test run succeeded");
                  return Curry._1(callback, 0);
                } else {
                  console.log("Test run failed");
                  return Curry._1(callback, 1);
                }
              }));
}

exports.runRoot = runRoot;
/* Respect Not a pure module */
