// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var Respect_ctx = require("./Respect_ctx.js");

var empty_004 = /* metadata */Respect_ctx.ContextMap[/* empty */0];

var empty = /* record */[
  /* name */"",
  /* children : [] */0,
  /* setups : [] */0,
  /* examples : [] */0,
  empty_004
];

function addChild(child, root) {
  return /* record */[
          /* name */root[/* name */0],
          /* children */Pervasives.$at(root[/* children */1], /* :: */[
                child,
                /* [] */0
              ]),
          /* setups */root[/* setups */2],
          /* examples */root[/* examples */3],
          /* metadata */root[/* metadata */4]
        ];
}

function addExample(ex, grp) {
  return /* record */[
          /* name */grp[/* name */0],
          /* children */grp[/* children */1],
          /* setups */grp[/* setups */2],
          /* examples */Pervasives.$at(grp[/* examples */3], /* :: */[
                ex,
                /* [] */0
              ]),
          /* metadata */grp[/* metadata */4]
        ];
}

function addSetup(code, grp) {
  return /* record */[
          /* name */grp[/* name */0],
          /* children */grp[/* children */1],
          /* setups */Pervasives.$at(grp[/* setups */2], /* :: */[
                code,
                /* [] */0
              ]),
          /* examples */grp[/* examples */3],
          /* metadata */grp[/* metadata */4]
        ];
}

var ExampleGroup = /* module */[
  /* empty */empty,
  /* addChild */addChild,
  /* addExample */addExample,
  /* addSetup */addSetup
];

var Ctx = 0;

exports.Ctx          = Ctx;
exports.ExampleGroup = ExampleGroup;
/* Respect_ctx Not a pure module */
