// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Map    = require("bs-platform/lib/js/map.js");
var Curry    = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");

var ContextMap = $$Map.Make([$$String.compare]);

function add(key, x, t) {
  t[/* data */0] = Curry._3(ContextMap[/* add */3], key, x, t[/* data */0]);
  return /* () */0;
}

function get(key, t) {
  return Curry._2(ContextMap[/* find */21], key, t[/* data */0]);
}

function create() {
  return /* record */[/* data */ContextMap[/* empty */0]];
}

exports.ContextMap = ContextMap;
exports.add        = add;
exports.get        = get;
exports.create     = create;
/* ContextMap Not a pure module */
